---
# Pipeline configuration for infrastructure deployment
terraform:
  version: "1.6.0"
  backend:
    bucket_name: "sideprojects-terraform-state"
    region: "sa-east-1"
    key: "vpc/terraform.tfstate"
