---
# Pipeline configuration for infrastructure deployment
terraform:
  version: "1.6.0"
  backend:
    bucket_name: "sideprojects-terraform-state"
    region: "us-east-1"
    key: "vpc/terraform.tfstate"
    dynamodb_table: "terraform-state-lock"

vpc:
  cidr_block: "10.0.0.0/16"
  enable_dns_hostnames: true
  enable_dns_support: true
  
  # Public subnets
  public_subnets:
    - cidr: "10.0.1.0/24"
      availability_zone: "us-east-1a"
    - cidr: "10.0.2.0/24"
      availability_zone: "us-east-1b"
  
  # Private subnets
  private_subnets:
    - cidr: "10.0.101.0/24"
      availability_zone: "us-east-1a"
    - cidr: "10.0.102.0/24"
      availability_zone: "us-east-1b"

environments:
  - dev
  - prod

tags:
  Project: "SideProjects"
  ManagedBy: "Terraform"
